In [11]:
# https://stackoverflow.com/questions/1801668/convert-a-list-with-strings-all-to-lowercase-or-uppercase

import pandas as pd
import numpy as np

In [12]:
# https://tabula-py.readthedocs.io/en/latest/getting_started.html

from tabula import read_pdf
df = read_pdf('Bexer_Test.pdf')

# df = pd.read_pdf('Bexer_Test.pdf')

df

'pages' argument isn't specified.Will extract only from page 1 by default.

[            Grantor       Grantee  Doc Type    Recorded    Doc Number  \
 0               NaN           NaN       NaN        Date           NaN
 1               NaN           NaN       NaN         NaN           NaN
 2      OLGUIN JESUS  SECRETARY OF  MORTGAGE   1/24/2023  2.023001e+10
 3    JULIAN, OLGUIN   HOUSING AND       NaN         NaN           NaN
 4        BELINDA A,         URBAN       NaN         NaN           NaN
 5               NaN  DEVELOPMENT,       NaN         NaN           NaN
 6   PEREZ HECTOR A,  SECRETARY OF  MORTGAGE   2/27/2023  2.023003e+10
 7    PEREZ MARIA J,   HOUSING AND       NaN         NaN           NaN
 8               NaN         URBAN       NaN         NaN           NaN
 9               NaN  DEVELOPMENT,       NaN         NaN           NaN
 10  DE HOYOS VIRGIL  SECRETARY OF  MORTGAGE   2/27/2023  2.023003e+10
 11     JR, DE HOYOS   HOUSING AND       NaN         NaN           NaN
 12      BERNADETTE,         URBAN       NaN         NaN           NaN
 13        RODRIGUEZ  DEVELOPMENT,       NaN         NaN           NaN
 14      AMANDA RAE,           NaN       NaN         NaN           NaN
 15    AGUILAR DULCE  SECRETARY OF  MORTGAGE   1/12/2023  2.023001e+10
 16         ARREOLA,   HOUSING AND       NaN         NaN           NaN
 17              NaN         URBAN       NaN         NaN           NaN
 18              NaN  DEVELOPMENT,       NaN         NaN           NaN
 19     BLAN ANTHONY  SECRETARY OF  MORTGAGE   1/13/2023  2.023001e+10
 20        DEMETRIC,   HOUSING AND       NaN         NaN           NaN
 21              NaN         URBAN       NaN         NaN           NaN
 22              NaN  DEVELOPMENT,       NaN         NaN           NaN
 23   MUNOZ ABIGAIL,  SECRETARY OF  MORTGAGE  12/27/2022  2.022029e+10
 24              NaN   HOUSING AND       NaN         NaN           NaN
 25              NaN         URBAN       NaN         NaN           NaN
 26              NaN  DEVELOPMENT,       NaN         NaN           NaN
 27              NaN           NaN       NaN         NaN           NaN
 28   WHITE VALARIE,  SECRETARY OF  MORTGAGE  12/28/2022  2.022029e+10
 29              NaN   HOUSING AND       NaN         NaN           NaN
 30              NaN         URBAN       NaN         NaN           NaN
 31              NaN  DEVELOPMENT,       NaN         NaN           NaN
 32              NaN           NaN       NaN         NaN           NaN

        Book/         Legal Description   Lot  Block      NCB County  \
 0    Volume/                       NaN   NaN    NaN      NaN  Block
 1       Page                       NaN   NaN    NaN      NaN    NaN
 2   --/--/--       Subdivision-  Name:  23.0    4.0  17264.0    NaN
 3        NaN   CARRIAGE HILLS  Lot: 23   NaN    NaN      NaN    NaN
 4        NaN     Block: 4 NCB: 17264,,   NaN    NaN      NaN    NaN
 5        NaN   Reference - 9555 / 117,   NaN    NaN      NaN    NaN
 6   --/--/--       Subdivision-  Name:  43.0   25.0  17293.0    NaN
 7        NaN    CARRIAGE HILLS Lot: 43   NaN    NaN      NaN    NaN
 8        NaN    Block: 25 NCB: 17293,,   NaN    NaN      NaN    NaN
 9        NaN    Reference - 9552 / 22,   NaN    NaN      NaN    NaN
 10  --/--/--       Subdivision-  Name:  52.0    1.0      NaN    NaN
 11       NaN         CHAMPIONS PARK #3   NaN    NaN      NaN    NaN
 12       NaN         Lot: 52 Block: 1,   NaN    NaN      NaN    NaN
 13       NaN   Reference - 9637 / 117,   NaN    NaN      NaN    NaN
 14       NaN                       NaN   NaN    NaN      NaN    NaN
 15  --/--/--       Subdivision-  Name:   2.0   13.0      NaN    NaN
 16       NaN     HERITAGE PARK #6 Lot:   NaN    NaN      NaN    NaN
 17       NaN  2 Block: 13, Reference -   NaN    NaN      NaN    NaN
 18       NaN               9509 / 118,   NaN    NaN      NaN    NaN
 19  --/--/--       Subdivision-  Name:   4.0    2.0      NaN    NaN
 20       NaN      BANDERA ROAD #1 Lot:   NaN    NaN      NaN    NaN
 21       NaN   4 Block: 2, Reference -   NaN    NaN      NaN    NaN
 22       NaN               9705 / 133,   NaN    NaN      NaN    NaN
 23  --/--/--       Subdivision-  Name:   3.0    5.0  12959.0    NaN
 24       NaN             WESTERN HILLS   NaN    NaN      NaN    NaN
 25       NaN        ADDITION #2 Lot: 3   NaN    NaN      NaN    NaN
 26       NaN     Block: 5 NCB: 12959,,   NaN    NaN      NaN    NaN
 27       NaN   Reference - 4600 / 163,   NaN    NaN      NaN    NaN
 28  --/--/--       Subdivision-  Name:   2.0  140.0      NaN    NaN
 29       NaN         OVERLOOK AT MEDIO   NaN    NaN      NaN    NaN
 30       NaN    CREEK #7 Lot: 2 Block:   NaN    NaN      NaN    NaN
 31       NaN  140, Reference - 20001 /   NaN    NaN      NaN    NaN
 32       NaN                     2423,   NaN    NaN      NaN    NaN

     Property Address
 0                NaN
 1                NaN
 2      7311 CARRIAGE
 3           RUN, SAN
 4    ANTONIO, TEXAS,
 5              78249
 6      7319 CARRIAGE
 7          BEND, SAN
 8    ANTONIO, TEXAS,
 9              78249
 10             11119
 11    UNBRIDLED, SAN
 12   ANTONIO, TEXAS,
 13             78245
 14               NaN
 15       3006 BEACON
 16          FLD, SAN
 17   ANTONIO, TEXAS,
 18             78245
 19         10529 FAR
 20     REACHES LANE,
 21   HELOTES, TEXAS,
 22             78023
 23  218 FRIDELL ST ,
 24      SAN ANTONIO,
 25      TEXAS, 78237
 26               NaN
 27               NaN
 28       10140 PEARL
 29        CREEK, SAN
 30   ANTONIO, TEXAS,
 31             78245
 32               NaN  ]

In [9]:
df = pd.read_csv('Bay_county_FL_5.csv')



df = df[df['Grantee'].str.contains('|'.join(elimkeys))==False]


from itables import show

# show(df , paging=True)


df = pd.read_csv('Bay_county_FL_5.csv')

dff= pd.DataFrame(df)
print(df)



df2 = df.pivot_table(index = ['Grantee'], aggfunc ='size')
print(df2)

  Status                                           Grantor  \
0      V                     BOOTH BARBARA A\nBOOTH PAUL S
1      V                               PHL INVESTMENTS LLC
2      V                               PHL INVESTMENTS LLC
3      V  PEREZ LUIS ALBERTO CUBAS\nPRADO DANIELA CARDENAS
4      V                  CLARK JAMES A JR\nCLARK KELSIE M
5      V                                KRASINSKAS KRISTEN

                                             Grantee Record Date  Doc Type  \
0                      SECRETARY OF VETERANS AFFAIRS     5/22/23  MORTGAGE
1                                       CADENCE BANK     5/22/23  MORTGAGE
2                                            CADENCE     5/22/23  MORTGAGE
3  MORTGAGE ELECTRONIC REGISTRATION SYSTEMS INC\n...     5/22/23  MORTGAGE
4                     REGIONS BANK\nREGIONS MORTGAGE     5/22/23  MORTGAGE
5                                 FIGURE LENDING LLC     5/22/23  MORTGAGE

  Book Type  Book  Page  Clerk File #  \
0        OR  4691   153    2023031446
1        OR  4690   168    2023031454
2        OR  4691   168    2023031454
3        OR  4691   184    2023031458
4        OR  4691   204    2023031461
5        OR  4691   250    2023031479

                                         Legal  DocLinks
0                L 56 PARKWAY DEVELOPERS INC\n       NaN
1                   UNIT 301 VISTA DEL MAR I\n       NaN
2                   UNIT 301 VISTA DEL MAR I\n       NaN
3                       L 56 CEDARS CROSSING\n       NaN
4           L 119 BREAKFAST POINT EAST PH 1B\n       NaN
5  L17 BLK 1 UNIT A JOHN G HENTZ JRS 1ST ADD\n       NaN
Grantee
CADENCE                                                                      1
CADENCE BANK                                                                 1
FIGURE LENDING LLC                                                           1
MORTGAGE ELECTRONIC REGISTRATION SYSTEMS INC\nTRUST MORTGAGE LENDING CORP    1
REGIONS BANK\nREGIONS MORTGAGE                                               1
SECRETARY OF VETERANS AFFAIRS                                                1
dtype: int64